services:
  drupal:
    image: drupal:9 # this will use the latest version of 1.23
    ports:
      - '8080:80' # expose 8080 on host and sent to 80 in container
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
  postgres:
    image: postgres:14  # this will use the latest apache v2
    environment:
      - POSTGRES_PASSWORD=myPassword