# version isn't needed as of 2020 for docker compose CLI. 
# All 2.x and 3.x features supported
# version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample HTML static site from https://startbootstrap.com/themes/agency/

services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-custom # building image with this name, following the docker file specified, with the relevant conf settings
    # without the image conf, the name of the image created will use the folder name to prevent naming conflicts
    ports:
      - '80:80'
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/
